### ISSUE TITLE
How to get the layer style

### ISSUE THREAD

**Issue by seuai** [meltingice/psd.js#107]
hello, 
please tell me how to get property of the layer style
(stroke, drop shadow, etc.)

**Comment by fabulousduck** [comment]
if you wish to get more detailed style info than `.tree()`, please take a look at `tree().descendants()[0]` and `node.get()`.

**Comment by joliejuke-orga** [comment]
```
let nodeFX = node.get('objectEffects').data; // data is not defined is the node has no fx options.
```
This property contains all the informations from the FX (also called blending options) from Photoshop. (e.g. Drop Shadow, Inner Shadow ...).

```
{
    data: {
		ebbl: [Object] // Bevel and Emboss
		FrFX: [Object] // Stroke - it's a more advanced borders styling. NOTE: Stroke has priority if borders is also defined.
		IrSh: [Object] // Inner Shadow
		IrGl: [Object] // Inner Glow
		ChFX: [Object] // Satin
		SoFi: [Object] // Color Overlay
		GrFl: [Object] // Gradient Overlay
		patternFill: [Object] // Pattern Overlay
		OrGl: [Object] // Outer Glov
		DrSh: [Object] // Drop Shadow
    }
}
```

**Comment by tinypoint** [comment]
> ```
> let nodeFX = node.get('objectEffects').data; 
> // data is not defined is the node has no fx options.
> ```
> 
> This property contains all the informations from the FX (also called blending options) from Photoshop. (e.g. Drop Shadow, Inner Shadow ...).
> 
> ```
> {
>     data: {
> 		ebbl: [Object] // Bevel and Emboss
> 		FrFX: [Object] // Stroke 
> 		IrSh: [Object] // Inner Shadow
> 		IrGl: [Object] // Inner Glow
> 		ChFX: [Object] // Satin
> 		SoFi: [Object] // Color Overlay
> 		GrFl: [Object] // Gradient Overlay
> 		patternFill: [Object] // Pattern Overlay
> 		OrGl: [Object] // Outer Glov
> 		DrSh: [Object] // Drop Shadow
>     }
> }
> ```

Great answer, but I got the layer style information now, how should I apply these styles to the node, I want to export to png, node.toPng() is definitely not working, I used the sharp package to Handling pictures, but I don't know how to restore color overlays, inner glows, etc.

**Comment by uea30475** [comment]
I didn't see the pattern image from patternFill, can we extract it?

> > ```
> > let nodeFX = node.get('objectEffects').data; 
> > // data is not defined is the node has no fx options.
> > ```
> > 
> > 
> > This property contains all the informations from the FX (also called blending options) from Photoshop. (e.g. Drop Shadow, Inner Shadow ...).
> > ```
> > {
> >     data: {
> > 		ebbl: [Object] // Bevel and Emboss
> > 		FrFX: [Object] // Stroke 
> > 		IrSh: [Object] // Inner Shadow
> > 		IrGl: [Object] // Inner Glow
> > 		ChFX: [Object] // Satin
> > 		SoFi: [Object] // Color Overlay
> > 		GrFl: [Object] // Gradient Overlay
> > 		patternFill: [Object] // Pattern Overlay
> > 		OrGl: [Object] // Outer Glov
> > 		DrSh: [Object] // Drop Shadow
> >     }
> > }
> > ```
> 
> Great answer, but I got the layer style information now, how should I apply these styles to the node, I want to export to png, `node.toPng()` is definitely not working, I used the [sharp](http://sharp.pixelplumbing.com/en/stable/api-constructor/) package to Handling pictures, but I don't know how to resolve the effect like color overlays, inner glows, etc.

I didn't see the pattern image from patternFill, can we extract it?

**Comment by ravigkp** [comment]
Please help to decode these info to image

**Comment by seuai** [comment]
> 이 정보를 이미지로 디코딩하는 데 도움을주세요

se the canvas.

**Comment by manchun224** [comment]
> > 이 정보를 이미지로 디코딩하는 데 도움을주세요
> 
> use the canvas.



> > > ```
> > > let nodeFX = node.get('objectEffects').data; 
> > > // data is not defined is the node has no fx options.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This property contains all the informations from the FX (also called blending options) from Photoshop. (e.g. Drop Shadow, Inner Shadow ...).
> > > ```
> > > {
> > >     data: {
> > > 		ebbl: [Object] // Bevel and Emboss
> > > 		FrFX: [Object] // Stroke 
> > > 		IrSh: [Object] // Inner Shadow
> > > 		IrGl: [Object] // Inner Glow
> > > 		ChFX: [Object] // Satin
> > > 		SoFi: [Object] // Color Overlay
> > > 		GrFl: [Object] // Gradient Overlay
> > > 		patternFill: [Object] // Pattern Overlay
> > > 		OrGl: [Object] // Outer Glov
> > > 		DrSh: [Object] // Drop Shadow
> > >     }
> > > }
> > > ```
> > 
> > 
> > Great answer, but I got the layer style information now, how should I apply these styles to the node, I want to export to png, `node.toPng()` is definitely not working, I used the [sharp](http://sharp.pixelplumbing.com/en/stable/api-constructor/) package to Handling pictures, but I don't know how to resolve the effect like color overlays, inner glows, etc.
> 
> I didn't see the pattern image or binary data of it from patternFill, how can I got it?

> Did you get the data at the end?

**Comment by seuai** [comment]
yers

**Comment by manchun224** [comment]
> yes

<img width="1127" alt="3872D49F-4749-410E-8FAD-5D796C53E799" src="https://user-images.githubusercontent.com/88648630/129009206-58d2502a-fe6b-44ae-b4de-f58a111a3312.png">
There is a default pattern on Mac, and there are additional preset patterns for each version. This is the additional preset pattern, The last part is the user-defined preset, which is embedded in the psd file，How to get pattern image or binary data ？

**Comment by MisakaCirno** [comment]
> ```
> let nodeFX = node.get('objectEffects').data; 
> // data is not defined is the node has no fx options.
> ```
> 
> This property contains all the informations from the FX (also called blending options) from Photoshop. (e.g. Drop Shadow, Inner Shadow ...).
> 
> ```
> {
>     data: {
> 		ebbl: [Object] // Bevel and Emboss
> 		FrFX: [Object] // Stroke 
> 		IrSh: [Object] // Inner Shadow
> 		IrGl: [Object] // Inner Glow
> 		ChFX: [Object] // Satin
> 		SoFi: [Object] // Color Overlay
> 		GrFl: [Object] // Gradient Overlay
> 		patternFill: [Object] // Pattern Overlay
> 		OrGl: [Object] // Outer Glov
> 		DrSh: [Object] // Drop Shadow
>     }
> }
> ```

I think this should probably be put in the README by the developers, it's critical information.

**Comment by MisakaCirno** [comment]
> ```
> let nodeFX = node.get('objectEffects').data; 
> // data is not defined is the node has no fx options.
> ```
> 
> This property contains all the informations from the FX (also called blending options) from Photoshop. (e.g. Drop Shadow, Inner Shadow ...).
> 
> ```
> {
>     data: {
> 		ebbl: [Object] // Bevel and Emboss
> 		FrFX: [Object] // Stroke 
> 		IrSh: [Object] // Inner Shadow
> 		IrGl: [Object] // Inner Glow
> 		ChFX: [Object] // Satin
> 		SoFi: [Object] // Color Overlay
> 		GrFl: [Object] // Gradient Overlay
> 		patternFill: [Object] // Pattern Overlay
> 		OrGl: [Object] // Outer Glov
> 		DrSh: [Object] // Drop Shadow
>     }
> }
> ```

Their names may change under some unknown conditions:
- `FrFX` or `frameFXMulti`
- `IrSh` or `innerShadowMulti`
- `SoFi` or `solidFillMulti`
- `GrFl` or `gradientFillMulti`
- `DrSh` or `dropShadowMulti`

**Comment by LarryHangFan** [comment]
> objectEffects

Excuse me, have you solved it?
