### ISSUE TITLE
Get the document resolution (DPI --> pixel/inch)

### ISSUE THREAD

**Issue by joliejuke-orga** [meltingice/psd.js#115]
Is it possible to get the document resolution.
I think this is an important feature since fonts size (in PT unit) should be computed from resolution.

**Comment by fabulousduck** [comment]
Hey @joliejuke-orga.

The root node of the document contains the Height and Width of the document with which you can calculate the resolution.

As for DPI, I have not been able to find anything about it in the official [doc](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/). So i think its safe to assume it is not stored in the file itself.

I did however find that at `0x0435` they store display data which may contain info about it.
I have not tested this yet tho as it is something i don't have time for (barely get time to answer these issues these days :( )

Regards Duck

**Comment by orthes** [comment]
I've run into the same issue. Official doc mentions resolution info being on `0x03ED`. I created #132 pull request to extract this information following example of [psd.rb](https://github.com/layervault/psd.rb/blob/31c7ddddfc96181847579833bf384532de3b29d9/lib/psd/resources/resolution_info.rb).
