### ISSUE TITLE
RangeError: Source is too large

### ISSUE THREAD

**Issue by Glinkis** [meltingice/psd.js#141]
After #139 I am getting an error when parsing one of my `psd` files:
``` 
RangeError: Source is too large
      at Uint8Array.set (native)
      at Image.combineRgbChannel (psd.js\lib\psd\image_modes\rgb.coffee:30:20)
``` 
The file in question is identical to other files (that works fine), except it's of the size 512 x 512 pixels.

**Comment by fabulousduck** [comment]
closing since fix got merged

**Comment by AnselDai** [comment]
Still encounter this situation. If make the size of unit8Array to be a parameter of PSD class, then we can dynamically control the size of Array in image.coffee according to the actual size of psd file
