### ISSUE TITLE
how to get text from texture layer?

### ISSUE THREAD

**Issue by zimengle** [meltingice/psd.js#18]
thanks

**Comment by darkfrog26** [comment]
I have the same frustration, but it's accessible if you do layer.export().text.

**Comment by meltingice** [comment]
If you have a layer node, you can do:

`node.get('typeTool').textValue`

**Comment by darkfrog26** [comment]
A bit better documentation would be greatly appreciated.

**Comment by meltingice** [comment]
For sure. It's something I plan on improving soon. Until then, the [README](https://github.com/meltingice/psd.js#accessing-layer-data) actually gives some info on how to do this.
