### ISSUE TITLE
How to use it in React

### ISSUE THREAD

**Issue by ruihanma** [meltingice/psd.js#185]
I am trying to use it in react with nextjs,
but when i import it, it shows 
`ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in /path/to/somewhere`.

thanks for guiding me

**Comment by ruihanma** [comment]
i'm using it by tag script
`<script src="/plugins/psd/psd.min.js" />`
`<script dangerouslySetInnerHTML={{ __html: `
      (function () {
        window.PSD = require('psd');
      })()
      `}} />`

is there any better way to use it?

**Comment by JASONPANGGO** [comment]
the should be used in Node.js.
child_process is a module from Node.js
https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html

**Comment by dave-wind** [comment]
if you use react no ssr 
you can see #138
if you use nextjs
you can use  next/head into your need page
example:

import React from 'react'
import Head from '@ctrip/nfes/next/head'
import { loadScript } from '../../utils/index'
const CustomScript = () => (
  <Head>
    <script>
      loadScript('https://cdn.bootcdn.net/ajax/libs/psd.js/3.2.0/psd.min.js',()=> {
        window.PSD = require('psd')
      })
    </script>
    <script></script>
  </Head>
)

export default CustomScript
