### ISSUE TITLE
How to identify superscript text?

### ISSUE THREAD

**Issue by AshDarkfold** [meltingice/psd.js#187]
I have a project which requires me to recreate the entire psd as an html file in their own way.
If I have a superscript text in my psd file, how do I know which text exactly is superscript and which is normal?

**Comment by qmalin** [comment]
I am also doing the same thing as you. I have encountered that the mask in the layer cannot be saved as png. Have you also encountered it?

**Comment by AshDarkfold** [comment]
Found a solution for this. The property called 'FontBaseline' can be exported from the typetool.coffee file. If it is 1 its superscript, 0 if normal.
