### ISSUE TITLE
How to export text with superscript and subscript characters

### ISSUE THREAD

**Issue by uea30475** [meltingice/psd.js#194]
`How can I export the text with superscript and subscript?
`
![image](https://user-images.githubusercontent.com/40632922/90304737-d541f200-dee4-11ea-9120-781a8404a633.png)
![image](https://user-images.githubusercontent.com/40632922/90304899-a9277080-dee6-11ea-9401-41878027776f.png)

**Comment by Sateesh2** [comment]
You can find it in typeTool data. It is called `FontBaseline ` 
you need to interpret the values as bellow 
0 - normal
1 - superScript 
2 - subScript
