### ISSUE TITLE
Somebody tried to parse Effects Layer?

### ISSUE THREAD

**Issue by Damon4** [meltingice/psd.js#20]
Thank you for your attention or help.

**Comment by Belakun** [comment]
Tried...unfortunately i get "undefined is not a function" on layer.get('objectEffects').export()

**Comment by hieulq0508g** [comment]
I also can not parse info objectEffects,
Can you help me

**Comment by gauravpadia** [comment]
Anybody was able to export effects layer or it is not possible at all ?

**Comment by chuyik** [comment]
It's definitely possible, since it's been written into the spec documentation.
See my PR on another parser library for details:
https://github.com/iamgqb/psd-parser/pull/9

**Comment by meltingice** [comment]
Try doing `layer.get('objectEffects').data`

**Comment by fabulousduck** [comment]
Im going to assume this was already solved as no further questions/issues were raised after @meltingice response

**Comment by manchun224** [comment]
> 尝试做 `layer.get('objectEffects').data`

I didn't see the pattern image or binary data of it from patternFill, how can I got it?
![image](https://user-images.githubusercontent.com/88648630/129384071-123f3a3b-e552-412d-9e55-9f89ba368754.png)
![image](https://user-images.githubusercontent.com/88648630/129384105-68b4c15a-9c0b-490a-8337-97d55df65193.png)
