### ISSUE TITLE
Bumping lodash version to maintain security

### ISSUE THREAD

**Issue by MgenGlder** [meltingice/psd.js#224]
Hello 👋🏾

We'd like to update that version of lodash to `4.17.21` to resolve outstanding security issue. Is this something that can be looked at? @fabulousduck We can open a PR and resolve this for you if you'd like.

cc @meltingice @fabulousduck 

edit: Created a pr with the update here: https://github.com/meltingice/psd.js/pull/226

**Comment by fabulousduck** [comment]
@MgenGlder With regards to the NPM situation, I don't have the credentials to update it myself, @meltingice will have to do that. But he has been MIA from this project for a long time now so I would not get my hopes up. If he does however want to bump this repo to the npm repo, that would be great :). 

As for your PR, the testing of a PR is for the creator of the PR to do. So once you can confirm to me that you have tested your change and does not break anything, I will be more than happy to merge the PR you have linked.

**Comment by MgenGlder** [comment]
@fabulousduck Fair enough, I can confirm we've tested the PR to the best of our ability. I was running into issues running the compilation scripts, I'm thinking it's because of how outdated the buildscripts/configuration are with the latest coffeescript compiler.I also noticed that the source controlled repo doesn't seem to match the latest version in NPM. As far as I'm aware the PR is good to go.

Do you have any context on this?

It seems the latest version of `psd.js` available on npm doesn't match what's shown in the releases in this repo.
After a fresh install I see this:
<img width="294" alt="Screen Shot 2021-09-21 at 4 32 37 PM" src="https://user-images.githubusercontent.com/8964151/134243499-bb537e13-b430-4ea7-8a13-56d0e23f78e6.png">

**Comment by MgenGlder** [comment]
@fabulousduck Managed to figure it out! There's a very similarly named package `psd.js` which seems to be forked and is authored by an entirely separate party. We have to be careful and have people understand this package represents `psd` and not any of the forks like `psd.js` etc.

**Comment by MgenGlder** [comment]
Seems like bumping the version introduces a small regression. `_.any` no longer exists, we can use `_.some` instead.

**Comment by MgenGlder** [comment]
@fabulousduck 👋🏾 Going to go ahead and merge this guy. I've verified the PSD rendering functionality still works. Should be a good win in getting this project out of security vulnerability pergatory.
