### ISSUE TITLE
How to get the properties of the text layer?

### ISSUE THREAD

**Issue by Dentada** [meltingice/psd.js#24]
I want to get the properties ( like font size, color) of the text layer, how can I do it?

**Comment by fnatik** [comment]
hi, do you know how can i export layers with there layer-style? tks

**Comment by meltingice** [comment]
@Dentada this is possible with version 2.1.0. You can do something like this:

``` js
type = node.get('typeTool')
type.fonts()
type.sizes()
type.alignment()
type.colors()
```

@fnatik can you clarify what you mean, please? Do you mean, export a layer image with the layer styles applied, or just export data about layer styles?

**Comment by fabulousduck** [comment]
No further info was provided and it is old enough to assume that @Dentada solved it himself as he did not respond any further.

**Comment by nibbr** [comment]
I have been looking for this answer about getting multiple fonts within a textbox. However, type.fonts() only lists the font names, it doesn't say what characters in the textbox should have the fonts applied to.

**Comment by yikfun** [comment]
> I have been looking for this answer about getting multiple fonts within a textbox. However, type.fonts() only lists the font names, it doesn't say what characters in the textbox should have the fonts applied to. Like for the colours we can use typeTool.engineData.EngineDict.StyleRun.RunLengthArray to get the positions of characters and typeTool.engineData.EngineDict.StyleRun.RunArray for the colours to apply to those characters right? But in typeTool.engineData.EngineDict.StyleRun.RunArray there is only 1 font listed although the text box has 2 fonts.
> 
> Also type.fonts() is showing repeated fonts and shoving an extra one in there that isn't actually in the PSD.
> 
> Anyone know how we can pull which font belongs to which characters?

+1
