### ISSUE TITLE
TypeError: PSD.open is not a function

### ISSUE THREAD

**Issue by hkshakib** [meltingice/psd.js#240]
let PSD = require('psd');
var file = process.argv[2] || './examples/images/example.psd';
var start = new Date();

PSD.open(file).then(function (psd) {
  return psd.image.saveAsPng('./output.png');
}).then(function () {
  console.log("Finished in " + ((new Date()) - start) + "ms");
});;

When I run this code, it shows the following error

**Comment by MgenGlder** [comment]
Hi @hkshakib, 
Which version are of `psd` are you using?

**Comment by MgenGlder** [comment]
Got a PR open that should resolve this.

PR: https://github.com/meltingice/psd.js/pull/244

**Comment by MgenGlder** [comment]
This should be fixed in the latest `3.4.0` release.
