### ISSUE TITLE
TypeError: PSD.fromFile is not a function

### ISSUE THREAD

**Issue by hzzly** [meltingice/psd.js#241]
version: 3.3.0
bug: 
![image](https://user-images.githubusercontent.com/16360684/137062346-cf936852-20c1-4918-a8d0-82513aa2b07f.png)

**Comment by MgenGlder** [comment]
And you are importing it this way: `import PSD from 'psd'` ?

**Comment by gregl83** [comment]
I just ran into this issue as well using npm to install latest of psd.

@Gasegamer - importing index.js worked for me, thanks!

**Comment by MgenGlder** [comment]
Have a pr that may resolve this so we don't have to do that wonky workaround, I'll do a bit of testing and work on a release.  
PR: https://github.com/meltingice/psd.js/pull/244

**Comment by phuongTP1998** [comment]
> PSD = require('./node_modules/psd/index');

It worked for me, thank you

**Comment by MgenGlder** [comment]
This should be fixed in the latest release `3.4.0`.

**Comment by phuongTP1998** [comment]
> This should be fixed in the latest release `3.4.0`.

good work
