### ISSUE TITLE
Not parsing font size properly

### ISSUE THREAD

**Issue by newelement** [meltingice/psd.js#26]
Greetings, I'm testing with a basic PSD file and I have 3 layers with text. All different sizes. And it's reporting two with size 5.58981 when the font size should be 16.8pt and another layer is getting parsed as 13 when it should be 65pt. Also, will the font weight be added soon?

**Comment by meltingice** [comment]
The font weight is actually included as a part of the font name. If you look at the font name, it's represented like `HelveticaNeue-Light` or `HelveticaNeue-Bold`.

Alternatively, there is some extra data in the styles hash that you can use. For example:

``` js
node.get('typeTool').styles().FauxBold[0] //= false
```

If it would help, I can build in parsing for the font weight to reduce the amount of boilerplate code.

**Comment by meltingice** [comment]
Regarding the font sizes - not sure what's up with that. Among the PSDs I've tested, it's parsed it correctly. Any chance you can post that PSD with the parsing issue?

**Comment by newelement** [comment]
Actually it would be nice if you could split up the styles if it's not too much work. Posting PSD shortly.

**Comment by newelement** [comment]
Here is a test PSD that reports the wrong font sizes. Now that I think about it. It may be due to the document DPI. https://www.dropbox.com/s/csz3ywkuytye582/Iphone_White.psd?dl=0

**Comment by newelement** [comment]
No, it's 72 dpi

**Comment by meltingice** [comment]
This is definitely what I would call a new and interesting bug. However, it's a bit weird that I've never run into this before. I think fixing it will mean finding out what's different about this particular PSD.

**Comment by newelement** [comment]
I actually have another PSD doing the same thing that came from my co-worker (designer). It is a rather large PSD though. 120MB

**Comment by meltingice** [comment]
So far the only major difference I've found is that the problem PSD was created on Windows, while most of the PSDs I've dealt with were created on OSX. Not sure if there's anything to that, but I'll keep looking.

**Comment by henry930** [comment]
I have seen the export JSON, the text value is like this: 
"text": { "value": "Why Choose US? Don’t you think ", "font": { "name": "AdobeInvisFont", "sizes": [ 72, 72, 90 ], "colors": [ [ 2, 2, 2, 255 ], [ 2, 2, 2, 255 ], [ 2, 2, 2, 255 ] ], "alignment": [ "left" ] }, 

and there is array of font-size, color etc.  But the value is only one. How to delimit which value is using which font or color??

**Comment by jide** [comment]
Seems to happen when the font has been resized afterwards. Try to select the text, then create a new text layer, you will see that the font size of this new layer is the size reported by PSD.js. When doing exactly the same text from scratch without resizing the font size is correct.

**Comment by safareli** [comment]
I also have 1.98pt reported be PSD.js as size of some text layer when it is actually 16pt. and as as @jide sad, i click in text layer and then click outside so that other text layer is created that new layer's size is 1.98pt.

**Comment by tylerjpeterson** [comment]
I've run into a similar issue in the past with every PSD parser I tried. Clicking around in the PSD would defeat the purpose of the project (automation), but was finally able to get PhotoShop reporting properly by applying the returned transform to the font size and line height manually. Seems to be a decade old PS bug that has yet to be resolved.

Hope it helps someone out - it nearly drove me insane...

```js
var data = node.export().text;
var transY = data.transform.yy; // 2.000077137715913
var fontSize = data.font.sizes[0]; // 15.99938 ✘
var lineHeight = data.font.leadings[0];  // 60 ✘

fontSize = Math.round((fontSize * transY) * 100) * 0.01; // 32 ✔
lineHeight = Math.round((fontSize * transY) * 100) * 0.01; // 64 ✔
```

**Comment by slash3b** [comment]
@tylerjpeterson  thank you!

**Comment by meltingice** [comment]
@tylerjpeterson have you found that you can do this calculation every time and it will always yield the correct size? Even when the font size is, in fact, stored correctly?

**Comment by tylerjpeterson** [comment]
@meltingice so far in my tests it works well regardless of whether or not the text box was transformed. In a case of there being no transform, the font size would effectively be multiplied by 1 with a little redundant / unnecessary rounding. 

I still see some slightly incorrect sizes reported on custom fonts from time to time, but usually within an acceptable deviation (1-5%). However, this happens independently of factoring in the transform when calculating font size. I believe it's entirely unrelated, and may be explained by disparities between desktop and web font files.

**Comment by fabulousduck** [comment]
As this issue was mostly resolved by the solution from @tylerjpeterson i am closing this. If this issue comes up again, please open a new issue for it.

**Comment by jide** [comment]
@RajeshBattu, see my comment https://github.com/meltingice/psd.js/issues/26#issuecomment-170095991

**Comment by jide** [comment]
Ah, I forgot, but the technique described by @tylerjpeterson here works perfectly and solves the issue : 
https://github.com/meltingice/psd.js/issues/26#issuecomment-192171777

**Comment by RajeshBattu** [comment]
I have tried the solution provided by @tylerjpeterson but its not working.  So i have commented before.  Please let me know if you want me to provide that PSD file to look into it.

**Comment by dpyzo0o** [comment]
@tylerjpeterson Hi, how can you get the lineHeight information? I cannot find the `leadings` property on the exported text object.

**Comment by tinhphantrong0612** [comment]
If your text has rotation, you should try:
```
var data = node.export().text;
var yx = data.transform.yx;
var yy = data.transform.yy;
var fontSize = data.font.sizes[0];

fontSize = Math.round((fontSize * Math.sqrt(yx * yx + yy * yy)) * 100) * 0.01;
```
