### ISSUE TITLE
Image Size?

### ISSUE THREAD

**Issue by darkfrog26** [meltingice/psd.js#27]
I can't find any examples of how to access the PSD width and height and any other meta information available on the PSD as a whole.

**Comment by darkfrog26** [comment]
I'm currently using psd.tree().get('width') but I'm not sure if that's the proper way to do it.

**Comment by darkfrog26** [comment]
Even if this is the correct way, I'd like a reference to what other values I can get.

**Comment by meltingice** [comment]
Yeah, that's the correct way to get the full PSD width. I'm currently working on documentation, which should help show all of the available data.

**Comment by fabulousduck** [comment]
This was resolved by the answer from @meltingice. Closing this.
