### ISSUE TITLE
Segmentation Fault on layer.export()

### ISSUE THREAD

**Issue by darkfrog26** [meltingice/psd.js#28]
I'm working my way through a PSD exporting each layer and on a specific PSD the 41st item of 125 throws a "Segmentation fault" when I call export() on it.  I have no further information provided to me beyond that.

**Comment by meltingice** [comment]
Can you find out what version it is? There is no native code in psd.js, including its dependencies, so it's probably an issue with your NodeJS installation.

**Comment by darkfrog26** [comment]
v0.10.31

**Comment by meltingice** [comment]
Strange... unfortunately there's not much I can do without the PSD. Either way, because psd.js has no native code, the segmentation fault must be a bug in NodeJS. Try change NodeJS versions or reinstalling NodeJS.

**Comment by darkfrog26** [comment]
Updated to 0.12.0 and it fixed it. Thanks for helping me pinpoint the issue.
