### ISSUE TITLE
gulp - Error: Parsing file psd.coffee: Line 1

### ISSUE THREAD

**Issue by borm** [meltingice/psd.js#29]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Parsing file /......../node_modules/psd/lib/psd.coffee: Line 1: Unexpected string
  at Deps.parseDeps (/......../node_modules/gulp-browserify/node_modules/browserify/node_modules/module-deps/index.js:339:28)

**Comment by meltingice** [comment]
What are you trying to do? It looks a little like you're trying to load the coffeescript directly without including coffeescript, so it's attempting to parse it as Javascript.

**Comment by meltingice** [comment]
I should add that if you include the `index.js` file in the root of the repository, or include the npm module normally, it will solve this problem for you.

**Comment by bORm** [comment]
Strangely enough, but successfully compiled after I require the module as require('node_modules/psd/lib/psd')

**Comment by bORm** [comment]
its not node.js

**Comment by bORm** [comment]
Run plz steps

Clone - https://github.com/bORm/psd.js

> npm install
> gulp

**Comment by bORm** [comment]
up

**Comment by xiaoyu2er** [comment]
@bORm is there any gulpfile?

**Comment by bORm** [comment]
@xiaoyu2er 
https://github.com/bORm/psd.js/blob/master/gulpfile.coffee

**Comment by christiansafka** [comment]
@bORm did you ever fix this?

**Comment by bORm** [comment]
No, I forgot about it)

**Comment by fabulousduck** [comment]
This thread is old enough to be closed based upon age and the fact that there was no further response from @borm if the issue was ever resolved or not.
