### ISSUE TITLE
How to get the image in the psd?

### ISSUE THREAD

**Issue by tim7004** [meltingice/psd.js#30]
Dear All,
I have using the https://github.com/meltingice/psd.js/blob/master/examples/images/example.psd file as an example. I would like to get the logo in the psd. When I use:
'document.getElementById('image').appendChild(psd.image.toPng());' I get the image of whole psd. How could I output the logo image only?

Thank you.

**Comment by meltingice** [comment]
You can do:

``` javascript
image = psd.tree().childrenAtPath('Version A/Logo_Glyph')[0].toPng();
document.getElementById('image').appendChild(image);
```

I didn't open the PSD so double check the path to the logo layer is right. Also, psd.js doesn't support gradient layer styles yet so it will only be a flat color.
