### ISSUE TITLE
How to recognized a layer is an image ?

### ISSUE THREAD

**Issue by tim7004** [meltingice/psd.js#31]
Dear All,
How to recognized a layer is an image?

Thank you.

**Comment by frankLife** [comment]
When layer is a text,there is a `typeTool` property that a image layer doesn't have.

**Comment by fabulousduck** [comment]
As there was never any confirmation of the solution from @frankLife solved the issue, i am closing this issue. (i can also confirm that @frankLife's answer does actually works from trying it myself)
