### ISSUE TITLE
Remove cakefile and move build steps into package.json

### ISSUE THREAD

**Issue by samccone** [meltingice/psd.js#4]
Having a cakefile means that a developer needs coffeescript installed globally\* to build this tool.

I propose to make this repo more portable by instead of using the task system within the cakefile to rather put the tasks as npm run-script tasks. Thus making the only dependency for building the tool node and npm.

> \* or they could use the installed bin version via ./node_modules/.bin/coffee

**Comment by fabulousduck** [comment]
Old and already solved. Closing this.
