### ISSUE TITLE
how to get the data of a single layer?

### ISSUE THREAD

**Issue by frankLife** [meltingice/psd.js#40]
I parse a psd file and print out the information of a single layer like this: 

```
console.log(psd.tree().descendants()[2]);
```

When I find there is a data property in the result.

```
{ layer:
    { file:
        { data: <Buffer 38 42 50 53 00 01 00 00 00 00 00 00 00 04 00 00 05 36 00 00 02 ee 00 08 00 03 00 00 00 00 00 00 75 30 38 42 49 4d 04 04 00 00 00 00 00 2f 1c 01 5a 00 ... >,
        pos: 838570 },
    header:
    { file: [Object],
        sig: '8BPS',
        version: 1,
        channels: 4,
        height: 1334,
        rows: 1334,
        width: 750,
        cols: 750,
        depth: 8,
        mode: 3 },
...
```

But when I invoke `fs.writeFileSync` to save the data of the layer, it saves the image of the psd.

Finally I find the data of every descendant is the same as the data of the whole psd

I also find that some other properties in descendant object such as `header.file.data` `mask.file.data` `blendMode.file.data` `image.file.data` are the same as `layer.file.data`.

So how to get the data of a single layer ?

**Comment by meltingice** [comment]
I'm a little confused on what you want the data for a single layer for. Are you trying to save just the image data for a single layer, or are you trying to create a new PSD with only the data from a single layer?

**Comment by frankLife** [comment]
I need to parse a psd file into a html so I need image data of a single layer to upload it to server.

As you say, every descendant has a reference to a file object and it has a data property . But it equals to the data of the whole psd. I can't find the data of the single layer.

like this: 

	console.log(psd.tree().descendants()[2].layer.file);
	console.log(psd.tree().descendants()[3].layer.file);
	
![same](http://gtms01.alicdn.com/tps/i1/TB11WvAJXXXXXX0apXXNR3tQXXX-481-121.png)

When I  print out two different layers' file object, these objects has the same data.

**Comment by meltingice** [comment]
If you're in NodeJS and want to export the layer image as a PNG you can do:

``` js
var png = psd.tree().descendants()[2].toPng()
// or...
psd.tree().descendants()[2].saveAsPng('path/to/output.png')
```

If you're parsing in the browser, you can export to an `<img>` element:

``` js
var img = psd.tree().descendants()[2].toPng()
```

If you want the raw pixel values:

``` js
psd.tree().descendants()[2].layer.image.pixelData
```

Hope that helps!

**Comment by frankLife** [comment]
Thanks very much.

Maybe all I need is the data( the data type of `buffer` in `nodejs`) that `saveAsPng` will use.

Can I get it ?

**Comment by KnightBubble** [comment]
i use like what you say, but throw error, 
```
layer.right = psd.header.width;
                              ^

TypeError: Cannot read property 'width' of null
  at Function.module.exports.Root.layerForPsd
```

**Comment by fabulousduck** [comment]
As this is a very old question, and an answer was already provided by @meltingice i am closing this issue. If @frankLife still has the issue, please open a new issue for it.

**Comment by AnselDai** [comment]
I encountered the same question. seems to have no answer here?

**Comment by AnselDai** [comment]
I am processing a 200MB psd file. When I get solidColor of a specified node, solidColor.parse() will cause `heap out of memory` error. So I am thinking if I can get the data of a single node and run parse(), I can avoid such error. Is there some method to get the Buffer data of a single layer?
