### ISSUE TITLE
How to distinguish layers with masks and shape layers?

### ISSUE THREAD

**Issue by kfitfk** [meltingice/psd.js#42]
When exporting a layer as PNG file, the result differs depending on the layer type. So I want to tell whether a layer is
- a shape layer / a fill layer with vector mask applied
- a layer with vector mask applied
- a layer with normal layer mask applied

I created a test file as shown below.
<img width="544" alt="PSD layer structure" src="https://cloud.githubusercontent.com/assets/2555626/9702085/1c81c44a-5481-11e5-9171-5f8f030a1964.png">

Now I go ahead and export each layer as a PNG file, I got the result like this.
<img width="515" alt="Export each PSD layer as a PNG file" src="https://cloud.githubusercontent.com/assets/2555626/9702128/6aa0fb86-5482-11e5-8809-5f764cae5d1c.png">

The two shape layers, or fill layers with vector masks, appears to be the same as they are in Photoshop when exported as PNG files. However, when a normal pixel layer has vector mask or layer mask applied, the exported PNG file only shows the layer content, regardless of the masks.

If I call the following method on each of these layers: shape_gradient, shape_solid_color, and vector_mask

`layer.get('vectorMask').paths`

The results are similar. I can't tell shape layers (or fill layers with vector masks) from normal pixel layers with vector masks.

And I don't know how to check if a layer has a normal layer mask applied. Looks like the `layer_mask.coffee` is dealing with a concept different from Photoshop's layer mask.

Any ideas how to distinguish these layers?

**Comment by gubi** [comment]
Hi,
for masks try to see inside the `layer` object.

``` javascript
psd.tree().descendants().forEach(function(node) {
        layers = node.clippingMask();
        if(node.layer.clipped) {
            // The layer has mask
             ...
       }
       ....
```

**Comment by fabulousduck** [comment]
This issue was resolved by @gubi from what i can read and is a good answer to the question. Therefore i am closing this issue.

**Comment by tinypoint** [comment]
> This issue was resolved by @gubi from what i can read and is a good answer to the question. Therefore i am closing this issue.

This js not a good answer. The answer is not helpful.

**Comment by tinypoint** [comment]
> > This issue was resolved by @gubi from what i can read and is a good answer to the question. Therefore i am closing this issue.
> 
> This is not a good answer. The answer is not helpful.
