### ISSUE TITLE
operate the PSD file

### ISSUE THREAD

**Issue by xiaowuming** [meltingice/psd.js#45]
Can you operate the PSD file?
Hide a layer and then save to the PNG file.

**Comment by shawn-northrop** [comment]
+1 I would like to export layer comps.

**Comment by fabulousduck** [comment]
@xiaowuming this is is possible by calling `.toPng()` on each layer except for the layer you wish to hide and then rendering each image onto each other either manually through manipulation of the buffer or by using a lib like `imagemagic` to do this.

The proposal for inbuilt operations like this do sound interesting and i will keep this open to see if this is something that we might want to implement in the vanilla rewrite of PSDJS.
