### ISSUE TITLE
Preview PSD in Browser

### ISSUE THREAD

**Issue by AK82** [meltingice/psd.js#53]
Hi,

I am trying to view the file example.psd in chrome, but without success.
Please tell me what I'm doing wrong.
Thank you.

This is my code:

```
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="../../dist/psd.min.js"></script>
</head>

<body>
  <div id="image"></div>

  <script type="text/javascript">
  (function () {
    var PSD = require('psd');

    PSD.fromURL("../images/example.psd").then(function(psd) {
      document.getElementById('image').appendChild(psd.image.toPng());
    });
  }());
  </script>
</body>
</html>
```

**Comment by meltingice** [comment]
Are you loading the webpage through a server or are you just opening the HTML directly in the browser? Due to browser security restrictions, the files have to be served through a server.

**Comment by AK82** [comment]
I tried to open the PSD directly in the browser.
Thank you.
