### ISSUE TITLE
Saving file from mask, blendMode, etc.

### ISSUE THREAD

**Issue by tomermes** [meltingice/psd.js#60]
Some objects contain a "file" object, which contains a binary data buffer.
How can one save the file as a png or anything simialr to that?

**Comment by meltingice** [comment]
The file object is just a reference to the full PSD file used during parsing. You can save the full preview image or any layer image data to a PNG by calling `saveAsPng`.

``` javascript
psd.image.saveAsPng('output.png');
psd.tree().children()[0].image.saveAsPng('output.png');
```

**Comment by tomermes** [comment]
Thanks for the quick response, maybe there's another way to what I'm trying to do - when a layer is clipped by another layer as a clipping mask, I'm trying to find which layer is masking which layer, all I can see in the layer is that it is clipped (layer.clipped == true)

**Comment by meltingice** [comment]
Once you get your layer/group node, you can call `clippingMask()` on it to get the layer that is clipping it. For example:

``` javascript
psd.tree().children()[0].clippingMask()
```

**Comment by fabulousduck** [comment]
As there was no further response from @tomermes and @meltingice provided a seemingly good answer to the question, i am closing this for now. If @tomermes still has the same question, please open a new issue for it.

**Comment by f2d** [comment]
```
psd.tree().children()[0].clippingMask()
```
This code returns me `null`, even in the simplest case like this: [test_mask.psd.zip](https://github.com/meltingice/psd.js/files/2544275/test_mask.psd.zip)

I had seen some other examples of accessing layer masks with psd.js, and none of them helped me yet.

**Comment by conor-kelleher** [comment]
@f2d The provided file does not have a clipping mask. It has a layer mask. These are different things. Clipping masks involve using multiple layers to provide a path to clip one another. (hence having this `clippingMask` function to find which layer clips the layer in question).

**Comment by f2d** [comment]
@conor-kelleher Thanks for explanation. In the end, I was able to use a layer mask by creating a canvas ImageData object with dimensions from `layer.mask.width` and `layer.mask.height` and writing `layer.image.maskData` array into its data property.

**Comment by wufangjian** [comment]
> @conor-kelleher Thanks for explanation. In the end, I was able to use a layer mask by creating a canvas ImageData object with dimensions from `layer.mask.width` and `layer.mask.height` and writing `layer.image.maskData` array into its data property.

Can give a simple example `code`？

**Comment by f2d** [comment]
@wufangjian Here is a simple example that works for me, `psd` variable holds a loaded PSD file, and the chain of children must be rewritten according to the actual file:
```
//* Get the layer data:

var layer = psd.tree().children()[1].children()[0].layer;
var mask = layer.mask;
var maskData = layer.image.maskData;

//* Save mask data to standard ImageData object:

var canvas = document.createElement('canvas');
var ctx = canvas.getContext('2d');
var w = canvas.width = mask.width;
var h = canvas.height = mask.height;
var imageData = ctx.createImageData(w,h);

imageData.data.set(maskData);
	
//* Save ImageData to canvas, then to image to test:

var img = new Image();

ctx.putImageData(imageData, 0,0);
img.src = canvas.toDataURL();
document.body.appendChild(img);
```
Note that a mask can have `mask.defaultColor` with value 0 or 255, meaning its background fill outside of its top/left/width/height can be black or white, decided by the program that saved the file. For example, layer mask created from active selection in SAI2 will have defaultColor 0, but a mask created without selection (so whole area is visible by default) will have defaultColor 255.

**Comment by beerus266** [comment]
@f2d Can you help me in my situation. Mask layer links folder instead of each children layer. How can i `toPng()` or do something to save **png** with all child layer which is clipped by mask. Thanks !
My structure PSD file: 
![here](https://user-images.githubusercontent.com/53264852/177692857-5a089c0f-7481-49a6-8302-b88236dc72a8.png)

**Comment by f2d** [comment]
@beerus266 
Blend an image of the folder contents first, layer by layer, then blend it with the mask image using `ctx.globalCompositeOperation = "destination-in";`.

P.S. See JS blend mode reference charts, like these:
http://buildnewgames.com/global-composit-operations/
https://galactic.ink/journal/2011/04/globalcompositeoperation/
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

**Comment by beerus266** [comment]
@f2d First, thanks for your answer. But I am not clear about 'Blend an image of the folder contents first, layer by layer'. I am a new developer about `psd.js`, so can you explain more detail about this. I will be happy if you make a example by code.

**Comment by f2d** [comment]
@beerus266 
I can certainly write example code for you or explain some basic concepts, if you are new not only to `psd.js`, but also JS canvas or JS in general.
Basically you create a canvas (see above example) with the width/height of the whole PSD, then put each layer in order like this:
```
ctx.globalCompositeOperation = layerBlendMode;
//* Must be converted from PSD naming to supported by JS canvas.

ctx.globalAlpha = layerOpacity;
//* Number from 0.0 to 1.0.

ctx.drawImage(layerImage, x, y);
```
Some names of blend modes in JS and PSD are equal, some not.
Some modes don't exist in JS at all (e.g. Linear Light) and must be emulated with calculation pixel-by-pixel, which is relatively slow.

But do you really need to do this in JS?
This library has no built-in renderer and there is a bit of work and complications involved in non-basic features possibly used in PSD files.
If you need some scripting, I heard Photoshop has it, although I'm not familiar, I don't even have Photoshop currently.
There are also several online projects that allow rendering PSD files in JS, to some degree of feature support, including [my project for sprite dress-up and export of versions](https://2draw.me/sprite_dress_up/).
You need to add at least one variable parameter to use my renderer, otherwise currently only the precomposed preview from the PSD is shown. For example, add `[100%]` to name of any layer, save the PSD and throw it into the page.
I was also thinking about wrapping the rendering part of my project into some reusable form, but that is still TODO.
Maybe all you need is already doable by some existing project.

What is your actual goal with PSD files?

**Comment by beerus266** [comment]
@f2d 
Your web project is outstanding. I try to upload file PSD to your web and it is exactly I want. And, in my sitiation:  
It is  [my PSD](https://drive.google.com/drive/u/1/folders/1uyaNF10FlheNqs5im0SGet37Dtu9s1lB). Layer at path `psd.tree().childrenAtPath('2/4/sketch')[0]` is a full hair image. 
![image](https://user-images.githubusercontent.com/53264852/177913490-2765ee3e-fc3c-44dc-bb06-c32641ae986d.png)

The folder at first folder `psd.tree().children()[0]` has a mask to crop all children children inside it. Can it export `toPng()` or `toBase64()` image like it: 
![image](https://user-images.githubusercontent.com/53264852/177914048-f6df51f6-61a6-4142-8a80-0ea3c052e395.png)

I try to write my own project to read and show image from PSD by Javascript

**Comment by f2d** [comment]
@beerus266
Currently `psd.js` has no rendering or blending methods, it only can give you layer content or mask content as is.
You have to blend it with you own coded steps.
There is also [ag-psd](https://github.com/Agamnentzar/ag-psd) library, also with no rendering methods, but may be simpler to use.
I use both `ag-psd` and `psd.js` in my project, by the way.

You did not say what your goal is.
Do you need to separately apply that mask to each layer in a folder and save each result?
Or do you just want to learn JS?
This place (issue tracker of someone's project) may not be the best place for this.

**Comment by beerus266** [comment]
@f2d I am sorry, I 'm missing your question. My goal is apply my mask to each layer in folder and save it to image **PNG** or url of **base64**. Can you example code using both `ag-psd` and `psd.js` to solve my issue ?

**Comment by f2d** [comment]
@beerus266 
Okay, first - an easy way to solve your issue (if I understand correctly) using an existing program.
Add `[parts]` text (exactly, including brackets) to the name of the top-most folder of your PSD, save it and throw into the [page that I mentioned earlier](https://2draw.me/sprite_dress_up/), click "Save all to PNG" button there, and you get 3 masked PNG files, one for each subfolder in PSD.

It may take more time to write complete code example and verify that it works, but if you still feel the need to develop something - you can try using available examples and research around the web, or wait for further help if the need is not pressing.

**Comment by beerus266** [comment]
@f2d 
I actually want to get 3 masked PNG files by `Javascript`, all process to export file PNG just only use coding. Can I get your contact: gmail, discord, .... But many thanks for everything you answered.
