### ISSUE TITLE
How to get data from layer

### ISSUE THREAD

**Issue by hieulq0508g** [meltingice/psd.js#62]
I 'm using "obj1.layer.mask" but it false some cases

Mask {
  file: 
   File {
     data: <Buffer 38 42 50 53 00 01 00 00 00 00 00 00 00 03 00 00 19 2a 00 00 05 ef 00 08 00 03 00 00 00 00 00 5b 5f 52 38 42 49 4d 04 04 00 00 00 00 00 97 1c 01 5a 00 ... >,
     pos: 100752008 },
  top: -1584,
  right: 1519,
  bottom: 4858,
  left: 0,
  size: 20,
  width: 1519,
  height: 6442,
  relative: false,
  disabled: false,
  invert: false,
  defaultColor: 255,
  flags: 0 }

![case 1](https://cloud.githubusercontent.com/assets/18589449/15705543/095fbaa8-281a-11e6-89ee-162e26c6334a.png)

**Comment by fabulousduck** [comment]
Im closing this for now as it is quite an old issue. If @hieulq0508g still has this question, please open a new issue for it and it will be looked at.
