### ISSUE TITLE
zIndex of layers ? 

### ISSUE THREAD

**Issue by fabulousduck** [meltingice/psd.js#69]
Is there a way of obtaining the zIndex of a layer if they are on the same level in the layer tree ? 
Cant use node.Depth for this since that looks at how deep it is in the layer structure, not the actual zIndex.

**Comment by meltingice** [comment]
There isn't a built-in method but you can do it easily enough.

``` js
node.siblings().indexOf(node)
```

**Comment by fabulousduck** [comment]
Closing as this was solved
