### ISSUE TITLE
layercomps

### ISSUE THREAD

**Issue by blancoberg** [meltingice/psd.js#75]
Hello,
Sorry for using this page for a general question. 

How do you obtain layer comp data that includes what params that is changed? There doesn't seem to be any available docs on the topic. The layer comp data that is provided by the example in the docs (tree().export())  doesn't give me much to work with.  

Thanks!

**Comment by fabulousduck** [comment]
try using  `tree().descendants()`

**Comment by fabulousduck** [comment]
Closing this issue as it is nearly a year old and @blancoberg hasn't responded since. If the issue still persists, please open a new issue for it.
