### ISSUE TITLE
error pngjs@0.4.0: The engine "node" is incompatible with this module. Expected version "0.8.x".

### ISSUE THREAD

**Issue by lvalencia** [meltingice/psd.js#84]
Hey, the company I work at is looking into using this project as part of an ingestion engine to process assets we receive from creative. We found that when using [yarn](https://code.facebook.com/posts/1840075619545360) this package fails to install. We believe the root cause of this to be linked to an outdated dependency, but we could be wrong. Below we have listed how to reproduce the issue what we expected and what we got as well as the environment info associated with development. 

Regards, and happy coding.

**Steps to Reproduce:**
`yarn add psd`

**Expected Result**
`yarn add v0.21.3`
`info No lockfile found.`
`[1/4] 🔍  Resolving packages...`
`[2/4] 🚚  Fetching packages...`
`[3/4] 🔗  Linking dependencies...`
`[4/4] 📃  Building fresh packages...`
`success Saved lockfile.`
`success Saved 10 new dependencies.`
`├─ coffee-script@1.7.1`
`├─ coffeescript-module@0.2.1`
`├─ iconv-lite@0.4.15`
`├─ jspack@0.0.4`
`├─ lodash@2.4.2`
`├─ mkdirp@0.3.5`
`├─ parse-engine-data@0.1.2`
`├─ pngjs@0.4.0`
`├─ psd@3.1.0`
`└─ rsvp@3.0.21`
`✨  Done in 1.82s.`

**Actual Result**
`yarn add v0.21.3`
`warning No license field`
`[1/4] 🔍  Resolving packages...`
`[2/4] 🚚  Fetching packages...`
`error pngjs@0.4.0: The engine "node" is incompatible with this module. Expected version "0.8.x".`
`error Found incompatible module`
`info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**Environment Info**
MacOS Sierra
Version 10.12.3

$ node --version
v7.7.1
$ npm --version
4.1.2
$ yarn --version
0.21.3

**Suspected Root Cause**
Outdated dependency in package.json line 22

**Temporary Workaround**
`yarn add psd --ignore-engines`
or use npm

**Comment by neekers** [comment]
+1

**Comment by cspotcode** [comment]
I just hit this problem, too.

`psd` [depends on `pngjs@0.4.0`](https://github.com/meltingice/psd.js/blob/8bcf7422b09d7bd00d35f49e87aab8763b5d83c1/package.json#L22)
`pngjs@0.4.0` [declares `"engine": {"node": "0.8.x"}`](https://github.com/lukeapage/pngjs/blob/v0.4.0/package.json#L11-L13)

The solution is to update the pngjs dependency to a newer version.  The earliest possible compatible version appears to be v1 ([here's the commit](https://github.com/lukeapage/pngjs/commit/880d1b0814a9f05c4633e47edfee7981dcf41318))

**Comment by fabulousduck** [comment]
@cspotcode would you be willing to make a PR solving this  ?

**Comment by fabulousduck** [comment]
I will look into this myself as this is such a small adjustment
